spring.application.name=KYC-SERVICE
# SWAGGER CONFIGURATION
springdoc.api-docs.path=/kyc/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Disable Config Server to ensure local startup
spring.cloud.config.enabled=false
spring.config.import=optional:configserver:http://localhost:7512

spring.datasource.url=jdbc:postgresql://localhost:5432/Kyc_Db
spring.datasource.username=postgres
spring.datasource.password=9305
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=7502

file.upload-dir=C:/Users/Asus/Desktop/Payment-wallet/kyc_uploads

eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

server.forward-headers-strategy=framework

# Swagger UI path
springdoc.swagger-ui.path=/swagger-ui.html

# API Docs path (Removed duplicate)
logging.file.name=logs/kyc-service.log
logging.level.root=INFO
logging.level.com.kyc=DEBUG

# MONITORING & METRICS
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
