spring.application.name=Transaction-Service
# SWAGGER
springdoc.api-docs.path=/api/transaction/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.cloud.config.enabled=false
spring.config.import=optional:configserver:http://localhost:7512

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

server.port=7506

eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

server.forward-headers-strategy=framework

logging.file.name=logs/transaction-service.log
logging.level.root=INFO
logging.level.com.transactions=DEBUG

# MONITORING & METRICS
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
