spring.application.name=user-service

spring.config.import=optional:configserver:http://localhost:7512

jwt.secret=mysupersecretkeymysupersecretkeymysupersecretkey
jwt.expiration=3600000

server.port=7500

spring.datasource.url=jdbc:postgresql://localhost:5432/User_Db
spring.datasource.username=postgres
spring.datasource.password=9305
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=srivastavaharsh148@gmail.com
spring.mail.password=jqsm stiv wzgb nhei

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

server.forward-headers-strategy=framework

# Swagger UI path
springdoc.swagger-ui.path=/swagger-ui.html

# API Docs path
springdoc.api-docs.path=/users/v3/api-docs

# Logging
logging.file.name=logs/user-service.log
logging.level.org.springframework=INFO
logging.level.com.user=DEBUG
logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web=DEBUG

# MONITORING & METRICS
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

logging.level.org.hibernate=INFO
logging.level.com.netflix=DEBUG
logging.level.root=INFO
