spring.application.name=Config-Servier

server.port=7512



# ===============================
# GIT CONFIG
# ===============================
spring.cloud.config.server.git.uri=https://github.com/HarshSrivastava12215211/Config-Server
spring.cloud.config.server.git.clone-on-start=true

# If private repo:
# spring.cloud.config.server.git.username=your-username
# spring.cloud.config.server.git.password=your-token

# ===============================
# LOGGING
# ===============================
logging.file.name=logs/config-server.log
logging.level.root=INFO

# MONITORING & METRICS
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

# EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
