spring.application.name=NOTIFICATION-SERVICE

spring.cloud.config.enabled=false
spring.config.import=optional:configserver:http://localhost:7512

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=7507

eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

server.forward-headers-strategy=framework

# Email Config (reuse User-Service SMTP settings)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=srivastavaharsh148@gmail.com
spring.mail.password=jqsm stiv wzgb nhei
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Swagger UI path
springdoc.swagger-ui.path=/swagger-ui.html

# API Docs path
springdoc.api-docs.path=/api/notifications/v3/api-docs

logging.file.name=logs/notification-service.log
logging.level.root=INFO
logging.level.com.notification=DEBUG

# MONITORING & METRICS
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}


