spring.application.name=PAYMENT-SERVICES
# SWAGGER
springdoc.api-docs.path=/api/payments/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.cloud.config.enabled=false
spring.config.import=optional:configserver:http://localhost:7512

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=7504

eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

server.forward-headers-strategy=framework

# Swagger UI path
springdoc.swagger-ui.path=/swagger-ui.html

# API Docs path (Removed duplicate)

# Razorpay Config (Testing Mode)
razorpay.api.key=rzp_test_SYf3NJn6LPhYax
razorpay.api.secret=ufb7OPYoligRMK2NrWoaCyPU
payment.gateway.fallback.enabled=true
services.wallet.url=http://wallet-service:7503
services.transaction.url=http://transaction-service:7506
services.user.url=http://user-service:7500

logging.file.name=logs/payment-services.log
logging.level.root=INFO
logging.level.com.payments=DEBUG

# MONITORING & METRICS
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}


# RESILIENCE4J CONFIGURATION
# Circuit Breaker
resilience4j.circuitbreaker.instances.paymentService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.paymentService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.paymentService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentService.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.paymentService.permittedNumberOfCallsInHalfOpenState=3

# Retry
resilience4j.retry.instances.paymentRetry.maxAttempts=3
resilience4j.retry.instances.paymentRetry.waitDuration=2000
resilience4j.retry.instances.paymentRetry.retryExceptions=feign.FeignException.InternalServerError,java.io.IOException
