spring.application.name=PAYMENT-SERVICES
# SWAGGER
springdoc.api-docs.path=/api/payments/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.cloud.config.enabled=false
spring.config.import=optional:configserver:http://localhost:7512

spring.datasource.url=jdbc:postgresql://localhost:5432/Payment_Db
spring.datasource.username=postgres
spring.datasource.password=9305
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=7504

eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

server.forward-headers-strategy=framework

# Swagger UI path
springdoc.swagger-ui.path=/swagger-ui.html

# API Docs path (Removed duplicate)

# Razorpay Config (Testing Mode)
razorpay.api.key=rzp_test_k9n6p7q8r9s0
razorpay.api.secret=abc123def456ghi789jkl0

logging.file.name=logs/payment-services.log
logging.level.root=INFO
logging.level.com.payments=DEBUG

# MONITORING & METRICS
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}


# RESILIENCE4J CONFIGURATION
# Circuit Breaker
resilience4j.circuitbreaker.instances.paymentService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.paymentService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.paymentService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentService.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.paymentService.permittedNumberOfCallsInHalfOpenState=3

# Retry
resilience4j.retry.instances.paymentRetry.maxAttempts=3
resilience4j.retry.instances.paymentRetry.waitDuration=2000
resilience4j.retry.instances.paymentRetry.retryExceptions=feign.FeignException.InternalServerError,java.io.IOException
