apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: payment-system
  labels:
    app: admin-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      initContainers:
        - name: wait-for-config
          image: busybox:1.36
          command: ['sh', '-c',
            'until wget -qO- http://config-server:7512/actuator/health | grep -q "UP"; do echo "Waiting for Config Server..."; sleep 5; done']
      containers:
        - name: admin-service
          image: harsh12215211/admin-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7501
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: DB_PORT
            - name: DB_NAME
              value: "admin_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: DB_PASSWORD
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "admin-service"
          resources:
            requests:
              memory: "256Mi"
              cpu: "10m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 7501
            initialDelaySeconds: 180
            timeoutSeconds: 10
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 7501
            initialDelaySeconds: 180
            timeoutSeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: payment-system
spec:
  selector:
    app: admin-service
  ports:
    - protocol: TCP
      port: 7501
      targetPort: 7501
  type: ClusterIP
