apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-service
  namespace: payment-system
  labels:
    app: chatbot-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: chatbot-service
  template:
    metadata:
      labels:
        app: chatbot-service
    spec:
      initContainers:
        - name: wait-for-eureka
          image: busybox:1.36
          command: ['sh', '-c',
            'until wget -qO- http://eureka-server:8761/actuator/health | grep -q "UP"; do echo "Waiting for Eureka..."; sleep 5; done']
      containers:
        - name: chatbot-service
          image: harsh12215211/chatbot-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7509
          env:
            - name: EUREKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: PORT
              value: "7509"
            - name: API_GATEWAY_URL
              value: "http://api-gateway:7505"
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: GEMINI_API_KEY
          resources:
            requests:
              memory: "128Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /docs
              port: 7509
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /docs
              port: 7509
            initialDelaySeconds: 40
            timeoutSeconds: 5
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  namespace: payment-system
spec:
  selector:
    app: chatbot-service
  ports:
    - protocol: TCP
      port: 7509
      targetPort: 7509
  type: ClusterIP
