apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: payment-system
  labels:
    app: config-server
spec:
  selector:
    app: config-server
  ports:
    - name: http
      port: 7512
      targetPort: 7512
  type: ClusterIP
